documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**

tests:
  - changed-files:
      - any-glob-to-any-file: tests/**
      - any-glob-to-any-file: thn_cli/syncv2/tests/**

syncv2:
  - changed-files:
      - any-glob-to-any-file: thn_cli/syncv2/**
      - any-glob-to-any-file: thn_cli/commands/commands_sync_*.py

routing:
  - changed-files:
      - any-glob-to-any-file: thn_cli/routing/**
      - any-glob-to-any-file: thn_cli/commands/commands_routing.py

blueprints:
  - changed-files:
      - any-glob-to-any-file: thn_cli/blueprints/**
      - any-glob-to-any-file: thn_cli/commands/commands_blueprint_*.py

ui:
  - changed-files:
      - any-glob-to-any-file: thn_cli/ui/**
      - any-glob-to-any-file: thn_cli/commands/commands_ui.py

plugins:
  - changed-files:
      - any-glob-to-any-file: thn_cli/plugins/**
